server:
  port: 8762
spring:
  application:
    name: service-hi-client
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
#      defaultZone: http://admin:111111@localhost:8761/eureka/
      defaultZone: http://admin:111111@eureka-server:8761/eureka/  # 部署到docker时，这个需要改为eureka-server


